#!/bin/bash

./configure \
    --prefix=/usr/local \
    --enable-exampledir=/usr/local/share/doc/frr/examples/ \
    --localstatedir=/usr/local/var/frr \
    --sbindir=/usr/local/sbin \
    --sysconfdir=/usr/local/etc \
    --libdir=/usr/local/lib \
    --enable-pimd \
    --enable-watchfrr \
    --enable-ospfclient=yes \
    --enable-ospfapi=yes \
    --enable-multipath=64 \
    --enable-user=frr \
    --enable-group=frr \
    --enable-vty-group=frrvty \
    --enable-configfile-mask=0640 \
    --enable-logfile-mask=0640 \
    --enable-rtadv \
    --enable-fpm \
    --enable-systemd=yes \
    --with-pkg-git-version \
    --with-pkg-extra-version=-LTEspeed
		#--enable-dev-build \
